spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: keycloak-sso-sample
            client-secret: 732a4f7d-a671-41a9-8d40-0f4ac8c646ef
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope:
              - openid
#            clientName: Yahoo! Japan
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8080/auth/realms/linker
#            authorization-uri: http://127.0.0.1:8080/auth/realms/linker/protocol/openid-connect/auth
#            token-uri: http://127.0.0.1:8080/auth/realms/linker/protocol/openid-connect/token
#            jwk-set-uri: http://127.0.0.1:8080/auth/realms/linker/protocol/openid-connect/certs
#            user-info-uri: http://127.0.0.1:8080/auth/realms/linker/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
server:
  port: 8081
