version: "3.8"

volumes:
  mysql_store:

services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_identity_access
      MYSQL_USER: user_identity_access
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_store:/var/lib/mysql

  keycloak:
    build: .
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: db_identity_access
      DB_USER: user_identity_access
      DB_SCHEMA: db_identity_access
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    volumes:
      - ./themes/linker-web:/opt/jboss/keycloak/themes/linker-web
    ports:
      - 8080:8080
    depends_on:
      - mysql
